// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.19.6
// source: proto/rig/v1/rig.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Ping struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Seq           uint64                 `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`        // monotonic per client; gap/duplicate detector
	Payload       []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"` // tunable size for F4 backpressure tests
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ping) Reset() {
	*x = Ping{}
	mi := &file_proto_rig_v1_rig_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ping) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ping) ProtoMessage() {}

func (x *Ping) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_rig_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ping.ProtoReflect.Descriptor instead.
func (*Ping) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_rig_proto_rawDescGZIP(), []int{0}
}

func (x *Ping) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *Ping) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Pong struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	AckSeq           uint64                 `protobuf:"varint,1,opt,name=ack_seq,json=ackSeq,proto3" json:"ack_seq,omitempty"`                                   // echoes Ping.seq
	ServerId         string                 `protobuf:"bytes,2,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`                              // which replica served this → F1 pinning evidence
	StreamOpenUnixMs int64                  `protobuf:"varint,3,opt,name=stream_open_unix_ms,json=streamOpenUnixMs,proto3" json:"stream_open_unix_ms,omitempty"` // when this stream opened → F3 drain analysis
	ConnStreamCount  uint64                 `protobuf:"varint,4,opt,name=conn_stream_count,json=connStreamCount,proto3" json:"conn_stream_count,omitempty"`      // streams multiplexed on this connection → F1/F2
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Pong) Reset() {
	*x = Pong{}
	mi := &file_proto_rig_v1_rig_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pong) ProtoMessage() {}

func (x *Pong) ProtoReflect() protoreflect.Message {
	mi := &file_proto_rig_v1_rig_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pong.ProtoReflect.Descriptor instead.
func (*Pong) Descriptor() ([]byte, []int) {
	return file_proto_rig_v1_rig_proto_rawDescGZIP(), []int{1}
}

func (x *Pong) GetAckSeq() uint64 {
	if x != nil {
		return x.AckSeq
	}
	return 0
}

func (x *Pong) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *Pong) GetStreamOpenUnixMs() int64 {
	if x != nil {
		return x.StreamOpenUnixMs
	}
	return 0
}

func (x *Pong) GetConnStreamCount() uint64 {
	if x != nil {
		return x.ConnStreamCount
	}
	return 0
}

var File_proto_rig_v1_rig_proto protoreflect.FileDescriptor

const file_proto_rig_v1_rig_proto_rawDesc = "" +
	"\n" +
	"\x16proto/rig/v1/rig.proto\x12\x06rig.v1\"2\n" +
	"\x04Ping\x12\x10\n" +
	"\x03seq\x18\x01 \x01(\x04R\x03seq\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\"\x97\x01\n" +
	"\x04Pong\x12\x17\n" +
	"\aack_seq\x18\x01 \x01(\x04R\x06ackSeq\x12\x1b\n" +
	"\tserver_id\x18\x02 \x01(\tR\bserverId\x12-\n" +
	"\x13stream_open_unix_ms\x18\x03 \x01(\x03R\x10streamOpenUnixMs\x12*\n" +
	"\x11conn_stream_count\x18\x04 \x01(\x04R\x0fconnStreamCount20\n" +
	"\x03Rig\x12)\n" +
	"\aSession\x12\f.rig.v1.Ping\x1a\f.rig.v1.Pong(\x010\x01B+Z)github.com/amangale/bidi-rig/proto/rig/v1b\x06proto3"

var (
	file_proto_rig_v1_rig_proto_rawDescOnce sync.Once
	file_proto_rig_v1_rig_proto_rawDescData []byte
)

func file_proto_rig_v1_rig_proto_rawDescGZIP() []byte {
	file_proto_rig_v1_rig_proto_rawDescOnce.Do(func() {
		file_proto_rig_v1_rig_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_rig_v1_rig_proto_rawDesc), len(file_proto_rig_v1_rig_proto_rawDesc)))
	})
	return file_proto_rig_v1_rig_proto_rawDescData
}

var file_proto_rig_v1_rig_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_rig_v1_rig_proto_goTypes = []any{
	(*Ping)(nil), // 0: rig.v1.Ping
	(*Pong)(nil), // 1: rig.v1.Pong
}
var file_proto_rig_v1_rig_proto_depIdxs = []int32{
	0, // 0: rig.v1.Rig.Session:input_type -> rig.v1.Ping
	1, // 1: rig.v1.Rig.Session:output_type -> rig.v1.Pong
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_rig_v1_rig_proto_init() }
func file_proto_rig_v1_rig_proto_init() {
	if File_proto_rig_v1_rig_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_rig_v1_rig_proto_rawDesc), len(file_proto_rig_v1_rig_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_rig_v1_rig_proto_goTypes,
		DependencyIndexes: file_proto_rig_v1_rig_proto_depIdxs,
		MessageInfos:      file_proto_rig_v1_rig_proto_msgTypes,
	}.Build()
	File_proto_rig_v1_rig_proto = out.File
	file_proto_rig_v1_rig_proto_goTypes = nil
	file_proto_rig_v1_rig_proto_depIdxs = nil
}
