// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.19.6
// source: proto/rig/v1/rig.proto

package v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Rig_Session_FullMethodName = "/rig.v1.Rig/Session"
)

// RigClient is the client API for Rig service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RigClient interface {
	// Bidirectional: client sends sequenced pings, server responds with
	// echo + the identity of the replica that served it.
	Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Ping, Pong], error)
}

type rigClient struct {
	cc grpc.ClientConnInterface
}

func NewRigClient(cc grpc.ClientConnInterface) RigClient {
	return &rigClient{cc}
}

func (c *rigClient) Session(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[Ping, Pong], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Rig_ServiceDesc.Streams[0], Rig_Session_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Ping, Pong]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Rig_SessionClient = grpc.BidiStreamingClient[Ping, Pong]

// RigServer is the server API for Rig service.
// All implementations must embed UnimplementedRigServer
// for forward compatibility.
type RigServer interface {
	// Bidirectional: client sends sequenced pings, server responds with
	// echo + the identity of the replica that served it.
	Session(grpc.BidiStreamingServer[Ping, Pong]) error
	mustEmbedUnimplementedRigServer()
}

// UnimplementedRigServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRigServer struct{}

func (UnimplementedRigServer) Session(grpc.BidiStreamingServer[Ping, Pong]) error {
	return status.Error(codes.Unimplemented, "method Session not implemented")
}
func (UnimplementedRigServer) mustEmbedUnimplementedRigServer() {}
func (UnimplementedRigServer) testEmbeddedByValue()             {}

// UnsafeRigServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RigServer will
// result in compilation errors.
type UnsafeRigServer interface {
	mustEmbedUnimplementedRigServer()
}

func RegisterRigServer(s grpc.ServiceRegistrar, srv RigServer) {
	// If the following call panics, it indicates UnimplementedRigServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Rig_ServiceDesc, srv)
}

func _Rig_Session_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(RigServer).Session(&grpc.GenericServerStream[Ping, Pong]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Rig_SessionServer = grpc.BidiStreamingServer[Ping, Pong]

// Rig_ServiceDesc is the grpc.ServiceDesc for Rig service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Rig_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rig.v1.Rig",
	HandlerType: (*RigServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Session",
			Handler:       _Rig_Session_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/rig/v1/rig.proto",
}
